Update ifup-eth
Update ifup-eth

diff --git a/network-scripts/ifup-eth b/network-scripts/ifup-eth
--- a/network-scripts/ifup-eth
+++ b/network-scripts/ifup-eth
@@ -293,21 +293,22 @@ else
 
             if ! LC_ALL=C ip addr ls ${REALDEVICE} | LC_ALL=C grep -q "${ipaddr[$idx]}/${prefix[$idx]}" ; then
                 if [ "${REALDEVICE}" != "lo" ] && ! is_false "${arpcheck[$idx]}"; then
-                    ARPING=$(/sbin/arping -c 2 -w ${ARPING_WAIT:-3} -D -I ${REALDEVICE} ${ipaddr[$idx]})
-                    if [ $? = 1 ]; then
-                        ARPINGMAC=$(echo $ARPING |  sed -ne 's/.*\[\(.*\)\].*/\1/p')
-                        if [ -n "${ARPINGMAC}" ]; then
-                            net_log $"Error, some other host ($ARPINGMAC) already uses address ${ipaddr[$idx]}."
-                            exit 1
-                        else
-                            ARPINGAGAIN=$(/sbin/arping -c 2 -w ${ARPING_WAIT:-3} -D -I ${REALDEVICE} ${ipaddr[$idx]})
-                            if [ $? = 1 ]; then
-                                ARPINGMACAGAIN=$(echo $ARPINGAGAIN |  sed -ne 's/.*\[\(.*\)\].*/\1/p')
-                                net_log $"Error, some other hosts ($ARPINGMACAGAIN) already uses address ${ipaddr[$idx]}."
+                    while [ $tries -lt $ARPING_TRIES ]
+                    do
+                        ARPING=$(/sbin/arping -c 2 -w ${ARPING_WAIT:-3} -D -I ${REALDEVICE} ${ipaddr[$idx]})
+                        if [ $? = 1 ]; then
+                            ARPINGMAC=$(echo $ARPING |  sed -ne 's/.*\[\(.*\)\].*/\1/p')
+                            net_log $"Error, some other host ($ARPINGMAC) already uses address ${ipaddr[$idx]}
+                            tries=$((tries+1))
+                            if [ $tries -eq $ARPING_TRIES ]
+                            then
+                                echo "arping failed after $tries tries"
                                 exit 1
                             fi
+                        else
+                            break
                         fi
-                    fi
+                    done
                 fi
 
                 if ! ip addr add ${ipaddr[$idx]}/${prefix[$idx]} \
