9.70-sync: sysconfig/network-scripts/* updated - part 2
  This commit contains a lot of whitespace changes.
  Use 'git diff --ignore-all-space' to display the relevant changes.

diff --git a/sysconfig/network-scripts/ifup-eth b/sysconfig/network-scripts/ifup-eth
--- a/sysconfig/network-scripts/ifup-eth
+++ b/sysconfig/network-scripts/ifup-eth
@@ -40,49 +40,49 @@ is_available ${REALDEVICE}
 if [ -n "${HWADDR}" ]; then
     FOUNDMACADDR=$(get_hwaddr ${REALDEVICE})
     if [ "${FOUNDMACADDR}" != "${HWADDR}" -a "${FOUNDMACADDR}" != "${MACADDR}" ]; then
-	    net_log $"Device ${DEVICE} has different MAC address than expected, ignoring."
-	    exit 1
+        net_log $"Device ${DEVICE} has different MAC address than expected, ignoring."
+        exit 1
     fi
 fi
 
 # If the device is a bridge, create it with brctl, if available.
 if [ "${TYPE}" = "Bridge" ]; then
-      if [ ! -x /usr/sbin/brctl ]; then
-	  net_log $"Bridge support not available: brctl not found"
-	  exit 1
-      fi
-      if [ ! -d /sys/class/net/${DEVICE}/bridge ]; then
-		/usr/sbin/brctl addbr -- ${DEVICE} || exit 1
-      fi
-      [ -n "${DELAY}" ] && /usr/sbin/brctl setfd -- ${DEVICE} ${DELAY}
-      [ -n "${STP}" ] && /usr/sbin/brctl stp -- ${DEVICE} ${STP}
-      [ -n "${PRIO}" ] && /usr/sbin/brctl setbridgeprio ${DEVICE} ${PRIO}
-      [ -n "${AGEING}" ] && /usr/sbin/brctl setageing ${DEVICE} ${AGEING}
-      # add the bits to setup driver parameters here
-      for arg in $BRIDGING_OPTS ; do
-          key=${arg%%=*};
-          value=${arg##*=};
-          if [ "${key}" != "multicast_router" -a "${key}" != "hash_max" -a "${key}" != "multicast_snooping" ]; then
-              echo $value > /sys/class/net/${DEVICE}/bridge/$key
-          fi
-      done
-      # set LINKDELAY (used as timeout when calling check_link_down())
-      # to at least (${DELAY} * 2) + 7 if STP is enabled. This is the
-      # minimum time required for /sys/class/net/$REALDEVICE/carrier to
-      # become 1 after "ip link set dev $DEVICE up" is called.
-      if [ "${STP}" = "yes" -o "${STP}" = "on" ]; then
-          TMPD=7
-          [ -n "${DELAY}" ] && TMPD=$(expr ${DELAY} \* 2 + ${TMPD})
-          [ 0$LINKDELAY -lt $TMPD ] && LINKDELAY=$TMPD
-      fi
+    if [ ! -x /usr/sbin/brctl ]; then
+        net_log $"Bridge support not available: brctl not found"
+        exit 1
+    fi
+    if [ ! -d /sys/class/net/${DEVICE}/bridge ]; then
+        /usr/sbin/brctl addbr -- ${DEVICE} || exit 1
+    fi
+    [ -n "${DELAY}" ] && /usr/sbin/brctl setfd -- ${DEVICE} ${DELAY}
+    [ -n "${STP}" ] && /usr/sbin/brctl stp -- ${DEVICE} ${STP}
+    [ -n "${PRIO}" ] && /usr/sbin/brctl setbridgeprio ${DEVICE} ${PRIO}
+    [ -n "${AGEING}" ] && /usr/sbin/brctl setageing ${DEVICE} ${AGEING}
+    # add the bits to setup driver parameters here
+    for arg in $BRIDGING_OPTS ; do
+        key=${arg%%=*};
+        value=${arg##*=};
+        if [ "${key}" != "multicast_router" -a "${key}" != "hash_max" -a "${key}" != "multicast_snooping" ]; then
+            echo $value > /sys/class/net/${DEVICE}/bridge/$key
+        fi
+    done
+    # set LINKDELAY (used as timeout when calling check_link_down())
+    # to at least (${DELAY} * 2) + 7 if STP is enabled. This is the
+    # minimum time required for /sys/class/net/$REALDEVICE/carrier to
+    # become 1 after "ip link set dev $DEVICE up" is called.
+    if [ "${STP}" = "yes" -o "${STP}" = "on" ]; then
+        TMPD=7
+        [ -n "${DELAY}" ] && TMPD=$(expr ${DELAY} \* 2 + ${TMPD})
+        [ 0$LINKDELAY -lt $TMPD ] && LINKDELAY=$TMPD
+    fi
 fi
 
 # Create tap device.
 if [ "${TYPE}" = "Tap" ]; then
-      [ -n "${OWNER}" ] && OWNER="user ${OWNER}"
-      TUNMODE="mode tap"
-      [[ ${DEVICE} == tun* ]] && TUNMODE="mode tun"
-      ip tuntap add ${TUNMODE} ${OWNER} dev ${DEVICE} > /dev/null
+    [ -n "${OWNER}" ] && OWNER="user ${OWNER}"
+    TUNMODE="mode tap"
+    [[ ${DEVICE} == tun* ]] && TUNMODE="mode tun"
+    ip tuntap add ${TUNMODE} ${OWNER} dev ${DEVICE} > /dev/null
 fi
 
 # Team master initialization.
@@ -92,12 +92,12 @@ fi
 
 # now check the real state
 is_available_wait ${REALDEVICE} ${DEVTIMEOUT} || {
-      if [ -n "$alias" ]; then
-         net_log $"$alias device ${DEVICE} does not seem to be present, delaying initialization."
-      else
-         net_log $"Device ${DEVICE} does not seem to be present, delaying initialization."
-      fi
-      exit 1
+    if [ -n "$alias" ]; then
+        net_log $"$alias device ${DEVICE} does not seem to be present, delaying initialization."
+    else
+        net_log $"Device ${DEVICE} does not seem to be present, delaying initialization."
+    fi
+    exit 1
 }
 
 
@@ -105,10 +105,10 @@ is_available_wait ${REALDEVICE} ${DEVTIMEOUT} || {
 # available as a configuration option in the config file, forcing the kernel
 # to think an ethernet card has a different MAC address than it really has.
 if [ -n "${MACADDR}" ]; then
-   ip link set dev ${DEVICE} address ${MACADDR}
+    ip link set dev ${DEVICE} address ${MACADDR}
 fi
 if [ -n "${MTU}" ]; then
-   ip link set dev ${DEVICE} mtu ${MTU}
+    ip link set dev ${DEVICE} mtu ${MTU}
 fi
 
 # is the device wireless? If so, configure wireless device specifics
@@ -125,8 +125,8 @@ fi
 if [ "${SLAVE}" = yes -a "${ISALIAS}" = no -a "${MASTER}" != "" ]; then
     install_bonding_driver ${MASTER}
     grep -wq "${DEVICE}" /sys/class/net/${MASTER}/bonding/slaves 2>/dev/null || {
-	/sbin/ip link set dev ${DEVICE} down
-	echo "+${DEVICE}" > /sys/class/net/${MASTER}/bonding/slaves 2>/dev/null
+        /sbin/ip link set dev ${DEVICE} down
+        echo "+${DEVICE}" > /sys/class/net/${MASTER}/bonding/slaves 2>/dev/null
     }
     ethtool_set
 
@@ -138,9 +138,9 @@ fi
 if [ "$ISALIAS" = no ] && is_bonding_device ${DEVICE} ; then
     install_bonding_driver ${DEVICE}
     /sbin/ip link set dev ${DEVICE} up
-    for device in $(LANG=C grep -l "^[[:space:]]*MASTER=\"\?${DEVICE}\"\?\([[:space:]#]\|$\)" /etc/sysconfig/network-scripts/ifcfg-*) ; do
-	    is_ignored_file "$device" && continue
-	    /sbin/ifup ${device##*/} || net_log "Unable to start slave device ${device##*/} for master ${DEVICE}." warning
+    for device in $(LANG=C grep -l "^[[:space:]]*MASTER=['\"]\?${DEVICE}['\"]\?\([[:space:]#]\|$\)" /etc/sysconfig/network-scripts/ifcfg-*) ; do
+        is_ignored_file "$device" && continue
+        /sbin/ifup ${device##*/} || net_log "Unable to start slave device ${device##*/} for master ${DEVICE}." warning
     done
 
     [ -n "${LINKDELAY}" ] && /bin/sleep ${LINKDELAY}
@@ -149,150 +149,161 @@ if [ "$ISALIAS" = no ] && is_bonding_device ${DEVICE} ; then
     for arg in $BONDING_OPTS ; do   
         key=${arg%%=*};
         value=${arg##*=};
-	if [ "${key}" = "primary" ]; then 
+        if [ "${key}" = "primary" ]; then 
             echo $value > /sys/class/net/${DEVICE}/bonding/$key
-	fi
+        fi
     done
 fi
 
 # If the device is part of a bridge, add the device to the bridge
 if [ -n "${BRIDGE}" ] && [ -x /usr/sbin/brctl ]; then
-      if [ ! -d /sys/class/net/${BRIDGE}/bridge ]; then
-	  /usr/sbin/brctl addbr -- ${BRIDGE} 2>/dev/null
-      fi
-      /sbin/ip addr flush dev ${DEVICE} 2>/dev/null
-      /sbin/ip link set dev ${DEVICE} up
-      ethtool_set
-      [ -n "${LINKDELAY}" ] && /bin/sleep ${LINKDELAY}
-      /usr/sbin/brctl addif -- ${BRIDGE} ${DEVICE}
-      # add the bits to setup driver parameters here
-      for arg in $BRIDGING_OPTS ; do
-          key=${arg%%=*};
-          value=${arg##*=};
-          echo $value > /sys/class/net/${DEVICE}/brport/$key
-      done
-      # Upon adding a device to a bridge,
-      # it's necessary to make radvd reload its config
-      [ -r /var/run/radvd/radvd.pid ] && kill -HUP $(cat /var/run/radvd/radvd.pid)
-      exit 0
+    if [ ! -d /sys/class/net/${BRIDGE}/bridge ]; then
+        /usr/sbin/brctl addbr -- ${BRIDGE} 2>/dev/null
+    fi
+    /sbin/ip addr flush dev ${DEVICE} 2>/dev/null
+    /sbin/ip link set dev ${DEVICE} up
+    ethtool_set
+    [ -n "${LINKDELAY}" ] && /bin/sleep ${LINKDELAY}
+    /usr/sbin/brctl addif -- ${BRIDGE} ${DEVICE}
+    # add the bits to setup driver parameters here
+    for arg in $BRIDGING_OPTS ; do
+        key=${arg%%=*};
+        value=${arg##*=};
+        echo $value > /sys/class/net/${DEVICE}/brport/$key
+    done
+    # Upon adding a device to a bridge,
+    # it's necessary to make radvd reload its config
+    [ -r /var/run/radvd/radvd.pid ] && kill -HUP $(cat /var/run/radvd/radvd.pid)
+    exit 0
 fi
-		     
+
 if [ -n "${DYNCONFIG}" ] && [ -x /sbin/dhclient ]; then
-    if [[ "${PERSISTENT_DHCLIENT}" =  [yY1]* ]]; then
-       ONESHOT="";
+    if is_true "${PERSISTENT_DHCLIENT}"; then
+        ONESHOT="";
     else
-       ONESHOT="-1";
+        ONESHOT="-1";
     fi;
     generate_config_file_name
     generate_lease_file_name
-    DHCLIENTARGS="${DHCLIENTARGS} -H ${DHCP_HOSTNAME:-${HOSTNAME%%.*}} ${ONESHOT} -q ${DHCLIENTCONF} -lf ${LEASEFILE} -pf /var/run/dhclient-${DEVICE}.pid"
+
+    if is_hostname_set; then
+        # We already have the hostname ->> send it to DHCP:
+        DHCLIENTARGS="${DHCLIENTARGS} -H ${DHCP_HOSTNAME:-${HOSTNAME%%.*}} ${ONESHOT} -q ${DHCLIENTCONF} -lf ${LEASEFILE} -pf /var/run/dhclient-${DEVICE}.pid"
+    else
+        # We need to acquire the hostname:
+        DHCLIENTARGS="${DHCLIENTARGS} ${DHCP_HOSTNAME:+-H $DHCP_HOSTNAME} ${ONESHOT} -q ${DHCLIENTCONF} -lf ${LEASEFILE} -pf /var/run/dhclient-${DEVICE}.pid"
+    fi
+
     echo
     echo -n $"Determining IP information for ${DEVICE}..."
-    if [[ "${PERSISTENT_DHCLIENT}" !=  [yY1]* ]] && check_link_down ${DEVICE}; then
-	echo $" failed; no link present.  Check cable?"
-	exit 1
+    if ! is_true "${PERSISTENT_DHCLIENT}" && check_link_down ${DEVICE}; then
+        echo $" failed; no link present.  Check cable?"
+        exit 1
     fi
 
     ethtool_set
 
     if /sbin/dhclient ${DHCLIENTARGS} ${DEVICE} ; then
-	echo $" done."
-	dhcpipv4="good"
+        echo $" done."
+        dhcpipv4="good"
     else
-	echo $" failed."
-	if [[ "${IPV4_FAILURE_FATAL}"  = [Yy1]* ]] ; then
-	    exit 1
-	fi
-	if [[ "$IPV6INIT" = [nN0]* || "$DHCPV6C" != [yY1]* ]] ; then
-	    exit 1
-	fi
-	net_log "Unable to obtain IPv4 DHCP address ${DEVICE}." warning
+        echo $" failed."
+        if is_true "${IPV4_FAILURE_FATAL}"; then
+            exit 1
+        fi
+        if is_false "$IPV6INIT" || ! is_true "$DHCPV6C"; then
+            exit 1
+        fi
+        net_log "Unable to obtain IPv4 DHCP address ${DEVICE}." warning
     fi
-# end dynamic device configuration
+    # end dynamic device configuration
 else 
     if [ -z "${IPADDR}" -a -z "${IPADDR0}" -a -z "${IPADDR1}" -a -z "${IPADDR2}" ]; then
-         # enable device without IP, useful for e.g. PPPoE
-	 ip link set dev ${REALDEVICE} up
-	 ethtool_set
-	 [ -n "${LINKDELAY}" ] && /bin/sleep ${LINKDELAY}
+        # enable device without IP, useful for e.g. PPPoE
+        ip link set dev ${REALDEVICE} up
+        ethtool_set
+        [ -n "${LINKDELAY}" ] && /bin/sleep ${LINKDELAY}
     else
-  
-    expand_config
 
-    [ -n "${ARP}" ] && \
-	ip link set dev ${REALDEVICE} $(toggle_value arp $ARP)
-   
-    if ! ip link set dev ${REALDEVICE} up ; then
-	net_log $"Failed to bring up ${DEVICE}."
-	exit 1
-    fi
+        expand_config
 
-    ethtool_set
+        [ -n "${ARP}" ] && \
+            ip link set dev ${REALDEVICE} $(toggle_value arp $ARP)
 
-    [ -n "${LINKDELAY}" ] && /bin/sleep ${LINKDELAY}
-
-    if [ "${DEVICE}" = "lo" ]; then
-    	SCOPE="scope host"
-    else
-        SCOPE=${SCOPE:-}
-    fi
-    
-    if [ -n "$SRCADDR" ]; then
-       SRC="src $SRCADDR"
-    else
-       SRC=
-    fi
-    
-    # set IP address(es)
-    for idx in {0..256} ; do
-	if [ -z "${ipaddr[$idx]}" ]; then
-            break
+        if ! ip link set dev ${REALDEVICE} up ; then
+            net_log $"Failed to bring up ${DEVICE}."
+            exit 1
         fi
 
-        if ! LC_ALL=C ip addr ls ${REALDEVICE} | LC_ALL=C grep -q "${ipaddr[$idx]}/${prefix[$idx]}" ; then
-            if [ "${REALDEVICE}" != "lo" ] && [ "${arpcheck[$idx]}" != "no" ] ; then
-                    /sbin/arping -q -c 2 -w 3 -D -I ${REALDEVICE} ${ipaddr[$idx]}
-                    if [ $? = 1 ]; then
-                        net_log $"Error, some other host already uses address ${ipaddr[$idx]}."
-                        exit 1
-                    fi
-            fi
+        ethtool_set
 
-            if ! ip addr add ${ipaddr[$idx]}/${prefix[$idx]} \
-              brd ${broadcast[$idx]:-+} dev ${REALDEVICE} ${SCOPE} label ${DEVICE}; then
-                net_log $"Error adding address ${ipaddr[$idx]} for ${DEVICE}."
-            fi
+        [ -n "${LINKDELAY}" ] && /bin/sleep ${LINKDELAY}
+
+        if [ "${DEVICE}" = "lo" ]; then
+            SCOPE="scope host"
+        else
+            SCOPE=${SCOPE:-}
         fi
 
         if [ -n "$SRCADDR" ]; then
-               sysctl -w "net.ipv4.conf.${SYSCTLDEVICE}.arp_filter=1" >/dev/null 2>&1
+            SRC="src $SRCADDR"
+        else
+            SRC=
         fi
 
-        # update ARP cache of neighboring computers
-        if [ "${REALDEVICE}" != "lo" ]; then
-          /sbin/arping -q -A -c 1 -I ${REALDEVICE} ${ipaddr[$idx]}
-          ( sleep 2;
-            /sbin/arping -q -U -c 1 -I ${REALDEVICE} ${ipaddr[$idx]} ) > /dev/null 2>&1 < /dev/null &
+        # set IP address(es)
+        for idx in {0..256} ; do
+            if [ -z "${ipaddr[$idx]}" ]; then
+                break
+            fi
+
+            if ! LC_ALL=C ip addr ls ${REALDEVICE} | LC_ALL=C grep -q "${ipaddr[$idx]}/${prefix[$idx]}" ; then
+                if [ "${REALDEVICE}" != "lo" ] && [ "${arpcheck[$idx]}" != "no" ] ; then
+                    ARPING=$(/sbin/arping -c 2 -w ${ARPING_WAIT:-3} -D -I ${REALDEVICE} ${ipaddr[$idx]})
+                    if [ $? = 1 ]; then
+                        ARPINGMAC=$(echo $ARPING |  sed -ne 's/.*\[\(.*\)\].*/\1/p')
+                        net_log $"Error, some other host ($ARPINGMAC) already uses address ${ipaddr[$idx]}."
+                        exit 1
+                    fi
+                fi
+
+                if ! ip addr add ${ipaddr[$idx]}/${prefix[$idx]} \
+                    brd ${broadcast[$idx]:-+} dev ${REALDEVICE} ${SCOPE} label ${DEVICE}; then
+                    net_log $"Error adding address ${ipaddr[$idx]} for ${DEVICE}."
+                fi
+            fi
+
+            if [ -n "$SRCADDR" ]; then
+                sysctl -w "net.ipv4.conf.${SYSCTLDEVICE}.arp_filter=1" >/dev/null 2>&1
+            fi
+
+            # update ARP cache of neighboring computers
+            if [ "${REALDEVICE}" != "lo" ]; then
+                /sbin/arping -q -A -c 1 -I ${REALDEVICE} ${ipaddr[$idx]}
+                ( sleep 2;
+                /sbin/arping -q -U -c 1 -I ${REALDEVICE} ${ipaddr[$idx]} ) > /dev/null 2>&1 < /dev/null &
+            fi
+
+            # set lifetime of address to forever
+            ip addr change ${ipaddr[$idx]}/${prefix[$idx]} dev ${REALDEVICE} valid_lft forever preferred_lft forever
+        done
+
+        # Set a default route.
+        if [ "${DEFROUTE}" != "no" ] && [ -z "${GATEWAYDEV}" -o "${GATEWAYDEV}" = "${REALDEVICE}" ]; then
+            # set up default gateway. replace if one already exists
+            if [ -n "${GATEWAY}" ] && [ "$(ipcalc --network ${GATEWAY} ${netmask[0]} 2>/dev/null)" = "NETWORK=${NETWORK}" ]; then
+                ip route replace default ${METRIC:+metric $METRIC} \
+                    ${EXTRA_ROUTE_OPTS} \
+                    via ${GATEWAY} ${WINDOW:+window $WINDOW} ${SRC} \
+                    ${GATEWAYDEV:+dev $GATEWAYDEV} ||
+                    net_log $"Error adding default gateway ${GATEWAY} for ${DEVICE}."
+            elif [ "${GATEWAYDEV}" = "${DEVICE}" ]; then
+                ip route replace default ${METRIC:+metric $METRIC} \
+                    ${EXTRA_ROUTE_OPTS} \
+                    ${SRC} ${WINDOW:+window $WINDOW} dev ${REALDEVICE} ||
+                    net_log $"Error adding default gateway for ${REALDEVICE}."
+            fi
         fi
-
-        # set lifetime of address to forever
-        ip addr change ${ipaddr[$idx]}/${prefix[$idx]} dev ${REALDEVICE} valid_lft forever preferred_lft forever
-    done
-
-    # Set a default route.
-    if [ "${DEFROUTE}" != "no" ] && [ -z "${GATEWAYDEV}" -o "${GATEWAYDEV}" = "${REALDEVICE}" ]; then
-	# set up default gateway. replace if one already exists
-	if [ -n "${GATEWAY}" ] && [ "$(ipcalc --network ${GATEWAY} ${netmask[0]} 2>/dev/null)" = "NETWORK=${NETWORK}" ]; then
-	    ip route replace default ${METRIC:+metric $METRIC} \
-		via ${GATEWAY} ${WINDOW:+window $WINDOW} ${SRC} \
-		${GATEWAYDEV:+dev $GATEWAYDEV} ||
-			net_log $"Error adding default gateway ${GATEWAY} for ${DEVICE}."
-	elif [ "${GATEWAYDEV}" = "${DEVICE}" ]; then
-	    ip route replace default ${METRIC:+metric $METRIC} \
-		${SRC} ${WINDOW:+window $WINDOW} dev ${REALDEVICE} ||
-			net_log $"Error adding default gateway for ${REALDEVICE}."
-	fi
-    fi
     fi
 fi
 
@@ -318,12 +329,21 @@ fi
 
 # IPv6 initialisation?
 /etc/sysconfig/network-scripts/ifup-ipv6 ${CONFIG}
-if [[ "${DHCPV6C}"  = [Yy1]* ]] && [ -x /sbin/dhclient ]; then
+if is_true "${DHCPV6C}" && [ -x /sbin/dhclient ]; then
     generate_config_file_name 6
     generate_lease_file_name 6
     echo
     echo -n $"Determining IPv6 information for ${DEVICE}..."
-    if /sbin/dhclient -6 -1 ${DHCPV6C_OPTIONS} ${DHCLIENTCONF} -lf ${LEASEFILE} -pf /var/run/dhclient6-${DEVICE}.pid -H ${DHCP_HOSTNAME:-${HOSTNAME%%.*}} ${DEVICE} ; then
+
+    if is_hostname_set; then
+        # We already have the hostname ->> send it to DHCP:
+        DHCLIENTARGS="-6 -1 ${DHCPV6C_OPTIONS} ${DHCLIENTCONF} -lf ${LEASEFILE} -pf /var/run/dhclient6-${DEVICE}.pid -H ${DHCP_HOSTNAME:-${HOSTNAME%%.*}} ${DEVICE}"
+    else
+        # We need to acquire the hostname:
+        DHCLIENTARGS="-6 -1 ${DHCPV6C_OPTIONS} ${DHCLIENTCONF} -lf ${LEASEFILE} -pf /var/run/dhclient6-${DEVICE}.pid ${DHCP_HOSTNAME:+-H $DHCP_HOSTNAME} ${DEVICE}"
+    fi
+
+    if /sbin/dhclient "$DHCLIENTARGS"; then
         echo $" done."
     else
         echo $" failed."
@@ -336,4 +356,3 @@ if [[ "${DHCPV6C}"  = [Yy1]* ]] && [ -x /sbin/dhclient ]; then
 fi
 
 exec /etc/sysconfig/network-scripts/ifup-post ${CONFIG} ${2}
-
diff --git a/sysconfig/network-scripts/ifup-ipv6 b/sysconfig/network-scripts/ifup-ipv6
--- a/sysconfig/network-scripts/ifup-ipv6
+++ b/sysconfig/network-scripts/ifup-ipv6
@@ -66,7 +66,7 @@ REALDEVICE=${DEVICE%%:*}
 DEVICE=$REALDEVICE
 
 # Test whether IPv6 configuration is disabled for this interface
-[[ "$IPV6INIT" = [nN0]* ]] && exit 0
+is_false "$IPV6INIT" && exit 0
 
 [ -f /etc/sysconfig/network-scripts/network-functions-ipv6 ] || exit 1
 . /etc/sysconfig/network-scripts/network-functions-ipv6
@@ -78,13 +78,13 @@ ipv6_test || exit 1
 # Test device status
 ipv6_test_device_status $DEVICE
 if [ $? != 0 -a $? != 11 ]; then
-	# device doesn't exist or other problem occurs
-	exit 1
+    # device doesn't exist or other problem occurs
+    exit 1
 fi
 
 # Setup IPv6 address on specified interface
 if [ -n "$IPV6ADDR" ]; then
-	ipv6_add_addr_on_device $DEVICE $IPV6ADDR || exit 1
+    ipv6_add_addr_on_device $DEVICE $IPV6ADDR || exit 1
 fi
 
 # Get current global IPv6 forwarding
@@ -92,213 +92,224 @@ ipv6_global_forwarding_current="$(/sbin/sysctl -e -n net.ipv6.conf.all.forwardin
 
 # Set some proc switches depending on defines
 if [ "$IPV6FORWARDING" = "yes" ]; then
-	# Global forwarding should be enabled
+    # Global forwarding should be enabled
 
-	# Check, if global IPv6 forwarding was already set by global script
-	if [ $ipv6_global_forwarding_current -ne 1 ]; then
-		net_log $"Global IPv6 forwarding is enabled in configuration, but not currently enabled in kernel"
-		net_log $"Please restart network with '/sbin/service network restart'"
-	fi
+    # Check, if global IPv6 forwarding was already set by global script
+    if [ $ipv6_global_forwarding_current -ne 1 ]; then
+        net_log $"Global IPv6 forwarding is enabled in configuration, but not currently enabled in kernel"
+        net_log $"Please restart network with '/sbin/service network restart'"
+    fi
 
-	ipv6_local_forwarding=1
-	ipv6_local_auto=0
-	if [ "$IPV6_ROUTER" = "no" ]; then
-		ipv6_local_forwarding=0
-	fi
-	if [ "$IPV6_AUTOCONF" = "yes" ]; then
-		ipv6_local_auto=1
-	fi
+    ipv6_local_forwarding=1
+    ipv6_local_auto=0
+    ipv6_local_accept_ra=0
+    if [ "$IPV6_ROUTER" = "no" ]; then
+        ipv6_local_forwarding=0
+    fi
+    if [ "$IPV6_AUTOCONF" = "yes" ]; then
+        ipv6_local_auto=1
+        ipv6_local_accept_ra=2
+    fi
 else
-	# Global forwarding should be disabled
+    # Global forwarding should be disabled
 
-	# Check, if global IPv6 forwarding was already set by global script
-	if [ $ipv6_global_forwarding_current -ne 0 ]; then
-		net_log $"Global IPv6 forwarding is disabled in configuration, but not currently disabled in kernel"
-		net_log $"Please restart network with '/sbin/service network restart'"
-	fi
+    # Check, if global IPv6 forwarding was already set by global script
+    if [ $ipv6_global_forwarding_current -ne 0 ]; then
+        net_log $"Global IPv6 forwarding is disabled in configuration, but not currently disabled in kernel"
+        net_log $"Please restart network with '/sbin/service network restart'"
+    fi
 
-	ipv6_local_forwarding=0
-	ipv6_local_auto=1
-	if [ "$IPV6_AUTOCONF" = "no" ]; then
-		ipv6_local_auto=0
-	fi
+    ipv6_local_forwarding=0
+    ipv6_local_auto=1
+    ipv6_local_accept_ra=1
+    if [ "$IPV6_AUTOCONF" = "no" ]; then
+        ipv6_local_auto=0
+        if [ ! "$IPV6_FORCE_ACCEPT_RA" = "yes" ]; then
+            ipv6_local_accept_ra=0
+        fi
+    fi
 fi
-/sbin/sysctl -e -w net.ipv6.conf.$SYSCTLDEVICE.forwarding=$ipv6_local_forwarding >/dev/null 2>&1
-/sbin/sysctl -e -w net.ipv6.conf.$SYSCTLDEVICE.accept_ra=$ipv6_local_auto >/dev/null 2>&1
-/sbin/sysctl -e -w net.ipv6.conf.$SYSCTLDEVICE.accept_redirects=$ipv6_local_auto >/dev/null 2>&1
-/sbin/sysctl -e -w net.ipv6.conf.$SYSCTLDEVICE.autoconf=$ipv6_local_auto >/dev/null 2>&1
+
+if [ ! "$IPV6_SET_SYSCTLS" = "no" ]; then
+    /sbin/sysctl -e -w net.ipv6.conf.$SYSCTLDEVICE.forwarding=$ipv6_local_forwarding >/dev/null 2>&1
+    /sbin/sysctl -e -w net.ipv6.conf.$SYSCTLDEVICE.accept_ra=$ipv6_local_accept_ra >/dev/null 2>&1
+    /sbin/sysctl -e -w net.ipv6.conf.$SYSCTLDEVICE.accept_redirects=$ipv6_local_auto >/dev/null 2>&1
+    /sbin/sysctl -e -w net.ipv6.conf.$SYSCTLDEVICE.autoconf=$ipv6_local_auto >/dev/null 2>&1
+fi
 
 # Set IPv6 MTU, if given
 if [ -n "$IPV6_MTU" ]; then
-	ipv6_set_mtu $DEVICE $IPV6_MTU
+    ipv6_set_mtu $DEVICE $IPV6_MTU
 fi
 
 # Setup additional IPv6 addresses from list, if given
 if [ -n "$IPV6ADDR_SECONDARIES" ]; then
-	for ipv6addr in $IPV6ADDR_SECONDARIES; do
-		ipv6_add_addr_on_device $DEVICE $ipv6addr
-	done
+    for ipv6addr in $IPV6ADDR_SECONDARIES; do
+        ipv6_add_addr_on_device $DEVICE $ipv6addr
+    done
 fi
 
 # Enable IPv6 RFC3041 privacy extensions if desired
 if [ "$IPV6_PRIVACY" = "rfc3041" ]; then
-	/sbin/sysctl -e -w net.ipv6.conf.$SYSCTLDEVICE.use_tempaddr=2 >/dev/null 2>&1
-	if [ $? -ne 0 ]; then
-		net_log $"Cannot enable IPv6 privacy method '$IPV6_PRIVACY', not supported by kernel"
-	fi
+    if [ ! "$IPV6_SET_SYSCTLS" = "no" ]; then
+        /sbin/sysctl -e -w net.ipv6.conf.$SYSCTLDEVICE.use_tempaddr=2 >/dev/null 2>&1
+        if [ $? -ne 0 ]; then
+            net_log $"Cannot enable IPv6 privacy method '$IPV6_PRIVACY', not supported by kernel"
+        fi
+    fi
 fi
 
 # Setup default IPv6 route, check are done by function
 if [ -n "$IPV6_DEFAULTDEV" -o -n "$IPV6_DEFAULTGW" ]; then
-	ipv6_set_default_route "$IPV6_DEFAULTGW" "$IPV6_DEFAULTDEV" "$DEVICE"
+    ipv6_set_default_route "$IPV6_DEFAULTGW" "$IPV6_DEFAULTDEV" "$DEVICE"
 fi
 
 # Setup additional static IPv6 routes on specified interface, if given
 if [ -f /etc/sysconfig/static-routes-ipv6 ]; then
-	LC_ALL=C grep -w "^$DEVICE" /etc/sysconfig/static-routes-ipv6 | while read device args; do
-		ipv6_add_route $args $DEVICE
-	done
+    LC_ALL=C grep -w "^$DEVICE" /etc/sysconfig/static-routes-ipv6 | while read device args; do
+        ipv6_add_route $args $DEVICE
+    done
 fi
 
 # Setup of 6to4, if configured
 if [ "$IPV6TO4INIT" = "yes" ]; then
-	valid6to4config="yes"
+    valid6to4config="yes"
 
-	# Test device status of 6to4 tunnel
-	ipv6_test_device_status tun6to4
-	if [ $? = 0 ]; then
-		# device is already up
-		net_log $"Device 'tun6to4' (from '$DEVICE') is already up, shutdown first"
-		exit 1
-	fi
+    # Test device status of 6to4 tunnel
+    ipv6_test_device_status tun6to4
+    if [ $? = 0 ]; then
+        # device is already up
+        net_log $"Device 'tun6to4' (from '$DEVICE') is already up, shutdown first"
+        exit 1
+    fi
 
-	# Get IPv4 address for global 6to4 prefix calculation
-	if [ -n "$IPV6TO4_IPV4ADDR" ]; then
-		# Take special configured from config file (precedence 1)
-		ipv4addr="$IPV6TO4_IPV4ADDR"
+    # Get IPv4 address for global 6to4 prefix calculation
+    if [ -n "$IPV6TO4_IPV4ADDR" ]; then
+        # Take special configured from config file (precedence 1)
+        ipv4addr="$IPV6TO4_IPV4ADDR"
 
-		# Get local IPv4 address from interface
-		ipv4addrlocal="$(ipv6_get_ipv4addr_of_device $DEVICE)"
-		if [ -z "$ipv4addrlocal" ]; then
-			# Take configured from config file
-			ipv4addrlocal="$IPADDR"
-		fi
-        else
-		# Get IPv4 address from interface first (has precedence 2)
-		ipv4addr="$(ipv6_get_ipv4addr_of_device $DEVICE)"
-		if [ -z "$ipv4addr" ]; then
-			# Take configured from config file (precedence 3)
-			ipv4addr="$IPADDR"
-		fi
-		ipv4addrlocal="$ipv4addr"
+        # Get local IPv4 address from interface
+        ipv4addrlocal="$(ipv6_get_ipv4addr_of_device $DEVICE)"
+        if [ -z "$ipv4addrlocal" ]; then
+            # Take configured from config file
+            ipv4addrlocal="$IPADDR"
+        fi
+    else
+        # Get IPv4 address from interface first (has precedence 2)
+        ipv4addr="$(ipv6_get_ipv4addr_of_device $DEVICE)"
+        if [ -z "$ipv4addr" ]; then
+            # Take configured from config file (precedence 3)
+            ipv4addr="$IPADDR"
+        fi
+        ipv4addrlocal="$ipv4addr"
+    fi
+
+    if [ -n "$ipv4addr" ]; then
+        if ! ipv6_test_ipv4_addr_global_usable $ipv4addr; then
+            net_log $"Given IPv4 address '$ipv4addr' is not globally usable" info
+            valid6to4config="no"
+        fi
+        if [ -z "$IPV6TO4_RELAY" ]; then
+            IPV6TO4_RELAY="192.88.99.1"
         fi
 
-	if [ -n "$ipv4addr" ]; then
-		if ! ipv6_test_ipv4_addr_global_usable $ipv4addr; then
-			net_log $"Given IPv4 address '$ipv4addr' is not globally usable" info
-	                valid6to4config="no"
-        	fi
-		if [ -z "$IPV6TO4_RELAY" ]; then
-			IPV6TO4_RELAY="192.88.99.1"
-		fi
-
-		# Check/generate relay address
-		ipv6to4_relay="$(ipv6_create_6to4_relay_address $IPV6TO4_RELAY)"
-		if [ $? -ne 0 ]; then
-			valid6to4config="no"
-		fi
-	else
-        	net_log $"IPv6to4 configuration needs an IPv4 address on related interface or otherwise specified" info
-		valid6to4config="no"
-	fi
-
-	# Setup 6to4 tunnel (hardwired name is "tun6to4"), if config is valid
-        if [ "$valid6to4config" = "yes" ]; then
-		# Get MTU of master device
-		ipv4mtu="$(/sbin/ip link show dev $DEVICE | awk '/\<mtu\>/ { print $5 }')"
-		if [ -n "$ipv4mtu" ]; then
-			# IPv6 tunnel MTU is IPv4 MTU minus 20 for IPv4 header
-			tunnelmtu=$(($ipv4mtu-20))
-		fi
-
-		if [ -n "$IPV6TO4_MTU" ]; then
-			if [ $IPV6TO4_MTU -gt $tunnelmtu ]; then
-				net_log $"Warning: configured MTU '$IPV6TO4_MTU' for 6to4 exceeds maximum limit of '$tunnelmtu', ignored" warning
-			else
-				tunnelmtu=$IPV6TO4_MTU
-			fi
-		fi
-
-		ipv6_add_6to4_tunnel tun6to4 $ipv4addr "" $tunnelmtu $ipv4addrlocal || exit 1
-
-		# Add route to for compatible addresses (removed later again)
-		ipv6_add_route "::/96" "::" tun6to4
-
-		# Add default route, if device matches
-		if [ "$IPV6_DEFAULTDEV" = "tun6to4" ]; then
-			if [ -n "$IPV6_DEFAULTGW" ]; then
-				net_log $"Warning: interface 'tun6to4' does not support 'IPV6_DEFAULTGW', ignored" warning
-			fi
-			ipv6_set_default_route $ipv6to4_relay tun6to4
-		fi
-
-		# Add static routes
-		if [ -f /etc/sysconfig/static-routes-ipv6 ]; then
-			LC_ALL=C grep -w "^tun6to4" /etc/sysconfig/static-routes-ipv6 | while read device network gateway; do
-				if [ -z "$network" ]; then
-					continue
-				fi
-				if [ -z "$gateway" ]; then
-					gateway="$ipv6to4_relay"
-				fi
-				ipv6_add_route $network $gateway tun6to4
-			done
-		fi
-
-		# Setup additional static IPv6 routes (newer config style)
-		if [ -f "/etc/sysconfig/network-scripts/route6-tun6to4" ]; then
-			sed -ne 's/#.*//' -e '/[^[:space:]]/p' /etc/sysconfig/network-scripts/route6-tun6to4 | while read line; do
-				if echo "$line" | LC_ALL=C grep -vq 'via'; then
-					# Add gateway if missing
-					line="$line via $ipv6to4_relay"
-				fi
-				/sbin/ip -6 route add $line
-			done
-		fi
-
-		# Cleanup autmatically generated autotunnel (not needed for 6to4)
-		/sbin/ip -6 route del ::/96 dev tun6to4
-		/sbin/ip -6 addr del "::$ipv4addrlocal/128" dev tun6to4
-
-	        if [ "$IPV6_CONTROL_RADVD" = "yes" ]; then
-			# RADVD is in use, so forwarding of IPv6 packets should be enabled, display warning
-			if [ $ipv6_global_forwarding_current -ne 1 ]; then
-				net_log $"Using 6to4 and RADVD IPv6 forwarding usually should be enabled, but it isn't" warning
-			fi
-
-		        if [ -n "$IPV6TO4_ROUTING" ]; then
-				ipv6to4prefix="$(ipv6_create_6to4_prefix $ipv4addr)"
-				if [ -n "$ipv6to4prefix" ]; then
-					# Add route to local networks
-					for devsuf in $IPV6TO4_ROUTING; do
-						dev="${devsuf%%-*}"
-						suf="$(echo $devsuf | awk -F- '{ print $2 }')"
-						ipv6_add_addr_on_device ${dev} ${ipv6to4prefix}${suf}
-					done
-				else
-					net_log $"Error occurred while calculating the IPv6to4 prefix"
-				fi
-			else
-				net_log $"radvd control enabled, but config is not complete"
-			fi
-
-			# Control running radvd
-			ipv6_trigger_radvd up "$IPV6_RADVD_TRIGGER_ACTION" $IPV6_RADVD_PIDFILE
-		fi
-	else
-		net_log $"6to4 configuration is not valid"
-		exit 1
+        # Check/generate relay address
+        ipv6to4_relay="$(ipv6_create_6to4_relay_address $IPV6TO4_RELAY)"
+        if [ $? -ne 0 ]; then
+            valid6to4config="no"
         fi
+    else
+        net_log $"IPv6to4 configuration needs an IPv4 address on related interface or otherwise specified" info
+        valid6to4config="no"
+    fi
+
+    # Setup 6to4 tunnel (hardwired name is "tun6to4"), if config is valid
+    if [ "$valid6to4config" = "yes" ]; then
+        # Get MTU of master device
+        ipv4mtu="$(/sbin/ip link show dev $DEVICE | awk '/\<mtu\>/ { print $5 }')"
+        if [ -n "$ipv4mtu" ]; then
+            # IPv6 tunnel MTU is IPv4 MTU minus 20 for IPv4 header
+            tunnelmtu=$(($ipv4mtu-20))
+        fi
+
+        if [ -n "$IPV6TO4_MTU" ]; then
+            if [ $IPV6TO4_MTU -gt $tunnelmtu ]; then
+                net_log $"Warning: configured MTU '$IPV6TO4_MTU' for 6to4 exceeds maximum limit of '$tunnelmtu', ignored" warning
+            else
+                tunnelmtu=$IPV6TO4_MTU
+            fi
+        fi
+
+        ipv6_add_6to4_tunnel tun6to4 $ipv4addr "" $tunnelmtu $ipv4addrlocal || exit 1
+
+        # Add route to for compatible addresses (removed later again)
+        ipv6_add_route "::/96" "::" tun6to4
+
+        # Add default route, if device matches
+        if [ "$IPV6_DEFAULTDEV" = "tun6to4" ]; then
+            if [ -n "$IPV6_DEFAULTGW" ]; then
+                net_log $"Warning: interface 'tun6to4' does not support 'IPV6_DEFAULTGW', ignored" warning
+            fi
+            ipv6_set_default_route $ipv6to4_relay tun6to4
+        fi
+
+        # Add static routes
+        if [ -f /etc/sysconfig/static-routes-ipv6 ]; then
+            LC_ALL=C grep -w "^tun6to4" /etc/sysconfig/static-routes-ipv6 | while read device network gateway; do
+                if [ -z "$network" ]; then
+                    continue
+                fi
+                if [ -z "$gateway" ]; then
+                    gateway="$ipv6to4_relay"
+                fi
+                ipv6_add_route $network $gateway tun6to4
+            done
+        fi
+
+        # Setup additional static IPv6 routes (newer config style)
+        if [ -f "/etc/sysconfig/network-scripts/route6-tun6to4" ]; then
+            sed -ne 's/#.*//' -e '/[^[:space:]]/p' /etc/sysconfig/network-scripts/route6-tun6to4 | while read line; do
+                if echo "$line" | LC_ALL=C grep -vq 'via'; then
+                    # Add gateway if missing
+                    line="$line via $ipv6to4_relay"
+                fi
+                /sbin/ip -6 route add $line
+            done
+        fi
+
+        # Cleanup autmatically generated autotunnel (not needed for 6to4)
+        /sbin/ip -6 route del ::/96 dev tun6to4
+        /sbin/ip -6 addr del "::$ipv4addrlocal/128" dev tun6to4
+
+        if [ "$IPV6_CONTROL_RADVD" = "yes" ]; then
+            # RADVD is in use, so forwarding of IPv6 packets should be enabled, display warning
+            if [ $ipv6_global_forwarding_current -ne 1 ]; then
+                net_log $"Using 6to4 and RADVD IPv6 forwarding usually should be enabled, but it isn't" warning
+            fi
+
+            if [ -n "$IPV6TO4_ROUTING" ]; then
+                ipv6to4prefix="$(ipv6_create_6to4_prefix $ipv4addr)"
+                if [ -n "$ipv6to4prefix" ]; then
+                    # Add route to local networks
+                    for devsuf in $IPV6TO4_ROUTING; do
+                        dev="${devsuf%%-*}"
+                        suf="$(echo $devsuf | awk -F- '{ print $2 }')"
+                        ipv6_add_addr_on_device ${dev} ${ipv6to4prefix}${suf}
+                    done
+                else
+                    net_log $"Error occurred while calculating the IPv6to4 prefix"
+                fi
+            else
+                net_log $"radvd control enabled, but config is not complete"
+            fi
+
+            # Control running radvd
+            ipv6_trigger_radvd up "$IPV6_RADVD_TRIGGER_ACTION" $IPV6_RADVD_PIDFILE
+        fi
+    else
+        net_log $"6to4 configuration is not valid"
+        exit 1
+    fi
 fi
 
 #wait for all global IPv6 addresses to leave the "tentative" state
