take embedded quotes out - it confuses gettext

diff --git a/sysconfig/network-scripts/ifup b/sysconfig/network-scripts/ifup
--- a/sysconfig/network-scripts/ifup
+++ b/sysconfig/network-scripts/ifup
@@ -31,7 +31,7 @@ CONFIG=${1}
 need_config ${CONFIG}
 
 [ -f "${CONFIG}" ] || {
-    echo $"$0: configuration for \"${1}\" not found." >&2
+    echo $"$0: configuration for ${1} not found." >&2
     echo $"Usage: ifup <device name>" >&2
     exit 1
 }
