fix more ifconfig greps (patch from Conectiva) fix a couple of typos

diff --git a/sysconfig/network-scripts/ifup-aliases b/sysconfig/network-scripts/ifup-aliases
--- a/sysconfig/network-scripts/ifup-aliases
+++ b/sysconfig/network-scripts/ifup-aliases
@@ -76,7 +76,7 @@ parent_device=$device
        #
 
 # sorry this is all one line -- it didn't work on multiple lines for me
-eval ` ifconfig | sed -e ' /^[^[:space:]]*:[0-9]*/ { s|^\([^:]*\):\([0-9]*\).*$|X=x; TMP="\2"; [ "$device" != "\1" ] \|\| |g; b; }; /^[^[:space:]]/ { s|.*|X=x; [ 0 = 0 ] \|\| |g; b; }; /inet addr:[0-9]*\.[0-9]*\.[0-9]*\.[0-9]* *Bcast:[0-9.]* *Mask:[0-9.]*/ { s|^.*inet addr:\(\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)\) *Bcast:\([0-9.]*\) *Mask:\([0-9.]*\).*$|eval " rdev_${TMP}_addr=\1; rdev_${TMP}_mb=\7_\6; rdevip_\2_\3_\4_\5=${TMP}; rdev_LIST=\\\\"\\\\$rdev_LIST \\\\${TMP}\\\\"; " \|\| |g; b; }; s|^.*$||g; ' ` X=x;
+eval `LC_ALL= LANG= ifconfig | sed -e ' /^[^[:space:]]*:[0-9]*/ { s|^\([^:]*\):\([0-9]*\).*$|X=x; TMP="\2"; [ "$device" != "\1" ] \|\| |g; b; }; /^[^[:space:]]/ { s|.*|X=x; [ 0 = 0 ] \|\| |g; b; }; /inet addr:[0-9]*\.[0-9]*\.[0-9]*\.[0-9]* *Bcast:[0-9.]* *Mask:[0-9.]*/ { s|^.*inet addr:\(\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)\) *Bcast:\([0-9.]*\) *Mask:\([0-9.]*\).*$|eval " rdev_${TMP}_addr=\1; rdev_${TMP}_mb=\7_\6; rdevip_\2_\3_\4_\5=${TMP}; rdev_LIST=\\\\"\\\\$rdev_LIST \\\\${TMP}\\\\"; " \|\| |g; b; }; s|^.*$||g; ' ` X=x;
 
 if [ -z "$rdev_LIST" ]; then
        no_devices_are_up=yes
@@ -148,7 +148,7 @@ function new_interface ()
        fi
 
        if [ -n "$devseen" ]; then
-              echo "error in $FILE: already seen device $parent_device:$DEVNUM\ in $devseen" >&2; exit 0
+              echo "error in $FILE: already seen device $parent_device:$DEVNUM in $devseen" >&2; exit 0
        fi
        
        if [ -z "$DEVICE" -o -z "$IPADDR" ]; then
@@ -218,7 +218,7 @@ function new_interface ()
                                setup_this=yes
                        fi
                        if [ -n "$rdev_mark" -a "$rdev_mark" != "$newmark" ]; then
-                               echo "error in ifcfg-${parent_device}:\* files" >&2 ; exit 0
+                               echo "error in ifcfg-${parent_device}: files" >&2 ; exit 0
                        fi
                        eval " rdev_${DEVNUM}_mark=\$newmark ";
                else
@@ -228,7 +228,7 @@ function new_interface ()
                if [ -n "$rdevip" -a "$rdevip" != "${DEVNUM}" ]; then
                        eval " mark_remove=\$rdev_${rdevip}_mark ";
                        if [ -n "$mark_remove" -a "$mark_remove" != "remove" ]; then
-                               echo "error in ifcfg-${parent_device}:\* files" >&2 ; exit 0
+                               echo "error in ifcfg-${parent_device}: files" >&2 ; exit 0
                        fi
                        if [ "$mark_remove" != "remove" ]; then
                                eval " rdev_${rdevip}_mark=remove ";
