Modify IPV6TO4_ROUTING to also add addresses on the interfaces Add RFC 3041 (IPv6 privacy) support (patch for both by Peter Bieringer <pb@bieringer.de>)

diff --git a/sysconfig/network-scripts/ifup-ipv6 b/sysconfig/network-scripts/ifup-ipv6
--- a/sysconfig/network-scripts/ifup-ipv6
+++ b/sysconfig/network-scripts/ifup-ipv6
@@ -4,17 +4,17 @@
 #
 #
 # Taken from:
-# (P) & (C) 2000-2004 by Peter Bieringer <pb@bieringer.de>
+# (P) & (C) 2000-2005 by Peter Bieringer <pb@bieringer.de>
 #
 #  You will find more information on the initscripts-ipv6 homepage at
 #   http://www.deepspace6.net/projects/initscripts-ipv6.html
 #
 # RHL integration assistance by Pekka Savola <pekkas@netcore.fi>
 #
-# Version 2004-03-21
+# Version 2005-09-22
 #
 # Note: if called (like normally) by /etc/sysconfig/network-scripts/ifup
-#        exit codes aren't handled by "ifup" 
+#        exit codes aren't handled by "ifup"
 #
 # Uses following information from "/etc/sysconfig/network":
 #  NETWORKING_IPV6=yes|no: controls IPv6 initialization (global setting)
@@ -31,14 +31,16 @@
 #    IPV6FORWARDING=yes: IPV6_AUTOCONF=no, IPV6_ROUTER=yes
 #    IPV6FORWARDING=no: IPV6_AUTOCONF=yes
 #  IPV6_MTU=<MTU for IPv6>: controls IPv6 MTU for this link (optional)
+#  IPV6_PRIVACY="rfc3041": control IPv6 privacy (optional)
+#    This script only supports "rfc3041" (if kernel supports it)
 #
 # Optional for 6to4 tunneling (hardwired name of tunnel device is "tun6to4"):
 #  IPV6TO4INIT=yes|no: controls 6to4 tunneling setup
 #  IPV6TO4_RELAY=<IPv4 address>: IPv4 address of the remote 6to4 relay (default: 192.88.99.1)
 #  IPV6TO4_MTU=<MTU for IPv6>: controls IPv6 MTU for the 6to4 link (optional, default is MTU of interface - 20)
 #  IPV6TO4_IPV4ADDR=<IPv4 address>: overwrite local IPv4 address (optional)
-#  IPV6TO4_ROUTING="<device>-<suffix>/<prefix length> ...": information to setup local subnetting
-#    Example: IPV6TO4_ROUTING="eth0-:f101::0/64 eth1-:f102::0/64"
+#  IPV6TO4_ROUTING="<device>-<suffix>/<prefix length> ...": information to setup additional interfaces
+#    Example: IPV6TO4_ROUTING="eth0-:f101::1/64 eth1-:f102::1/64"
 #
 # Optional for 6to4 tunneling to trigger radvd:
 #  IPV6_CONTROL_RADVD=yes|no: controls radvd triggering (optional)
@@ -48,18 +50,18 @@
 #  Required version of radvd to use 6to4 prefix recalculation
 #   0.6.2p3 or newer supporting option "Base6to4Interface"
 #  Required version of radvd to use dynamic ppp links
-#   0.7.0 + fixes or newer 
+#   0.7.0 + fixes or newer
 #
 
 
-. /etc/sysconfig/network 
+. /etc/sysconfig/network
 
 cd /etc/sysconfig/network-scripts
-. network-functions 
+. network-functions
 
 CONFIG=$1
 [ -f "$CONFIG" ] || CONFIG=ifcfg-$CONFIG
-source_config  
+source_config
 
 # IPv6 don't need aliases anymore, config is skipped
 REALDEVICE=`echo ${DEVICE} | sed 's/:.*//g'`
@@ -83,7 +85,7 @@ ipv6_test_device_status $DEVICE
 if [ $? != 0 -a $? != 11 ]; then
 	# device doesn't exist or other problem occurs
 	exit 1
-fi 
+fi
 
 # Setup IPv6 address on specified interface
 if ! [ -z "$IPV6ADDR" ]; then
@@ -140,6 +142,14 @@ if [ -n "$IPV6ADDR_SECONDARIES" ]; then
 	for ipv6addr in $IPV6ADDR_SECONDARIES; do
 		ipv6_add_addr_on_device $DEVICE $ipv6addr
 	done
+fi
+
+# Enable IPv6 RFC3041 privacy extensions if desired
+if [ "$IPV6_PRIVACY" = "rfc3041" ]; then
+	ipv6_exec_sysctl -w net.ipv6.conf.$DEVICE.use_tempaddr=2 >/dev/null 2>&1
+	if [ $? -ne 0 ]; then
+		echo $"Cannot enable IPv6 privacy method '$IPV6_PRIVACY', not supported by kernel"
+	fi
 fi
 
 # Setup default IPv6 route, check are done by function
@@ -284,7 +294,7 @@ if [ "$IPV6TO4INIT" = "yes" ]; then
 					for devsuf in $IPV6TO4_ROUTING; do
 						dev="`echo $devsuf | awk -F- '{ print $1 }'`"
 						suf="`echo $devsuf | awk -F- '{ print $2 }'`"
-						ipv6_add_route ${ipv6to4prefix}$suf :: $dev
+						ipv6_add_addr_on_device ${dev} ${ipv6to4prefix}${suf}
 					done
 				else
 					echo $"Error occurred while calculating the IPv6to4 prefix"
diff --git a/sysconfig/network-scripts/network-functions-ipv6 b/sysconfig/network-scripts/network-functions-ipv6
--- a/sysconfig/network-scripts/network-functions-ipv6
+++ b/sysconfig/network-scripts/network-functions-ipv6
@@ -8,7 +8,7 @@
 #  You will find more information on the initscripts-ipv6 homepage at
 #   http://www.deepspace6.net/projects/initscripts-ipv6.html
 #
-# Version: 2005-03-03
+# Version: 2005-09-22
 #
 #
 
@@ -419,12 +419,12 @@ ipv6_cleanup_routes() {
 	if [ -n "$gatewaymatch" ]; then
 		# Get all IPv6 routes (except default link-local and multicast) through given interface via a given gateway and remove them
 		ipv6_exec_ip -6 route show dev $device via $gatewaymatch | LC_ALL=C grep -v -w expires | LC_ALL=C egrep -v "^fe80::/64|^ff00::/8" | while read ipv6net dummy; do
-			ipv6_exec_ip -6 route del $ipv6net via $gatewaymatch dev $iface
+			ipv6_del_route $ipv6net $gatewaymatch $device
 		done
 	else
 		# Get all IPv6 routes (except default link-local and multicast) through given interface and remove them
 		ipv6_exec_ip -6 route show dev $device | LC_ALL=C grep -v -w expires | LC_ALL=C egrep -v "^fe80::/64|^ff00::/8" | while read ipv6net dummy; do
-			ipv6_exec_ip -6 route del $ipv6net dev $iface
+			ipv6_del_route $ipv6net :: $device
 		done
 	fi
 
@@ -589,6 +589,35 @@ ipv6_cleanup_device() {
 	# Remove all IPv6 addresses on this interface
 	ipv6_exec_ip -6 addr flush dev $device scope global >/dev/null 2>&1
 	ipv6_exec_ip -6 addr flush dev $device scope site   >/dev/null 2>&1
+
+	return 0
+}
+
+
+## Remove all IPv6 6to4 related routes and addresses on given interface
+#  $1: <Interface>
+# return code: 0=ok 1=argument error 2=IPv6 test fails 3=major problem
+ipv6_cleanup_6to4_device() {
+	local fn="ipv6_cleanup_6to4_device"
+
+	local device=$1
+
+	if [ -z "$device" ]; then
+		ipv6_log $"Missing parameter 'device' (arg 1)" err $fn
+		return 1
+	fi
+
+	ipv6_test testonly || return 2
+
+	# Cleanup 6to4 addresses on this device
+	ipv6_exec_ip -6 addr show dev $dev scope global permanent | LC_ALL=C grep -w inet6 | awk '{ print $2}' | LC_ALL=C grep "^2002:" | while read addr; do
+        	ipv6_del_addr_on_device ${dev} ${addr}
+	done
+
+	# Get all IPv6 routes through given interface via a given gateway and remove them
+	ipv6_exec_ip -6 route show dev $device | LC_ALL=C grep "^2002:" | while read ipv6net dummy; do
+		ipv6_del_route $ipv6net :: $device
+	done
 
 	return 0
 }
