start checking for link again

diff --git a/sysconfig/network-scripts/ifup b/sysconfig/network-scripts/ifup
--- a/sysconfig/network-scripts/ifup
+++ b/sysconfig/network-scripts/ifup
@@ -151,6 +151,11 @@ if [ -n "${DYNCONFIG}" ]; then
        DHCPCDARGS="${DHCPCDARGS} -R"
     fi
     echo -n $"Determining IP information for ${DEVICE}..."
+    if check_link_down ${DEVICE}; then
+	echo $" failed; no link present.  Check cable?"
+	ip link set down ${DEVICE} >/dev/null 2>&1
+	exit 1
+    fi
 
     # DHCP clients need DNS to be available, and we don't know
     # what DNS server they're using until they are done.
