fix typo

diff --git a/sysconfig/network-scripts/ifup-aliases b/sysconfig/network-scripts/ifup-aliases
--- a/sysconfig/network-scripts/ifup-aliases
+++ b/sysconfig/network-scripts/ifup-aliases
@@ -149,7 +149,7 @@ function new_interface ()
        fi
 
        if [ -n "$devseen" ]; then
-              echo $"error in $FILE: already seen device $parent_device:$DEVNUM\ in $devseen" >&2; exit 0
+              echo $"error in $FILE: already seen device $parent_device:$DEVNUM in $devseen" >&2; exit 0
        fi
        
        if [ -z "$DEVICE" -o -z "$IPADDR" ]; then
