return link up in check_link_down for EINVAL too; in fact, return link up if mii-tool fails for any reason

diff --git a/sysconfig/network-scripts/network-functions b/sysconfig/network-scripts/network-functions
--- a/sysconfig/network-scripts/network-functions
+++ b/sysconfig/network-scripts/network-functions
@@ -122,8 +122,11 @@ check_link_down ()
     if [ -x /sbin/mii-tool ]; then
         LC_ALL=C ip link show $1 2>/dev/null| grep -q UP || ip link set $1 up >/dev/null 2>&1
 	sleep 2
+	/sbin/mii-tool >/dev/null 2>&1 || return 1
 	output=`LC_ALL=C /sbin/mii-tool $1 2>&1`
 	if echo $output | grep -q "Operation not supported"; then
+	    return 1
+	elif echo $output | grep -q "Invalid argument"; then
 	    return 1
 	elif echo $output | grep -q "link ok"; then
 	    return 1
