fix killproc logic (only one success/failure per call)

diff --git a/rc.d/init.d/functions b/rc.d/init.d/functions
--- a/rc.d/init.d/functions
+++ b/rc.d/init.d/functions
@@ -97,14 +97,16 @@ killproc() {
 		if [ "$notset" = 1 ] ; then
 		       if ps h $pid>/dev/null 2>&1; then
 			   # TERM first, then KILL if not dead
-			   kill -TERM $pid && success "$base shutdown" || failure "$base shutdown"
+			   kill -TERM $pid
+			   #&& success "$base shutdown" || failure "$base shutdown"
 			   usleep 100000
 			   if ps h $pid >/dev/null 2>&1 ; then
 				sleep 1
 				if ps h $pid >/dev/null 2>&1 ; then
 				        sleep 3
 					if ps h $pid >/dev/null 2>&1 ; then
-					   kill -KILL $pid && success "$base shutdown" || failure "$base shutdown"
+					   kill -KILL $pid
+					   #&& success "$base shutdown" || failure "$base shutdown"
 					fi
 				fi
 			   fi
@@ -112,12 +114,14 @@ killproc() {
 		# use specified level only
 		else
 		        if ps h $pid >/dev/null 2>&1; then
-	                	kill $killlevel $pid && success "$base shutdown" || failure "$base shutdown"
+	                	kill $killlevel $pid 
+				#&& success "$base shutdown" || failure "$base shutdown"
 			fi
 		fi
 	else
 	    failure "$base shutdown"
 	fi
+	ps h $pid >/dev/null 2>&1 && failure "$base shutdown" || success "$base shutdown"
 
         # Remove pid file if any.
         rm -f /var/run/$base.pid
