change i18n stuff around; don't call gettext explicitly, just do echo $"some string"

diff --git a/rc.d/init.d/functions b/rc.d/init.d/functions
--- a/rc.d/init.d/functions
+++ b/rc.d/init.d/functions
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #
 # functions	This file contains functions to be used by most or all
 #		shell scripts in the /etc/init.d directory.
@@ -54,49 +54,6 @@ else
    INITLOG_ARGS=
 fi
 
-if [ -z "$GP_LANG" -a -f /etc/sysconfig/i18n ]; then
-   GP_LANG=$(sed -n 's/"//g ; s/^LANG=//p' /etc/sysconfig/i18n )
-fi
-
-gprintf() {
-        if [ -x /usr/bin/gettext ]; then 
-	   local TEXT=`LC_MESSAGES=$GP_LANG gettext -e --domain=$TEXTDOMAIN "$1"`
-	else
-	   local TEXT=$1
-	fi
-	[ "${1#*\\n}" ] || TEXT="$TEXT\n"
-	shift
-	printf "$TEXT" "$@"
-}	
-
-# Frontend to gprintf (support up to 4 %s in format string)
-# returns the message transleted in GPRINTF_MSG and
-# the resting parms in GPRINTF_REST
-# This simplifies a lot the call of functions like action,
-# now with i18n support
-gprintf_msg_rest() {
-case "$1" in
-       *%s*%s*%s*%s*)
-               GPRINTF_MSG=$(gprintf "$1" "$2" "$3" "$4" "$5")
-               shift 5;;
-       *%s*%s*%s*)
-               GPRINTF_MSG=$(gprintf "$1" "$2" "$3" "$4")
-               shift 4;;
-       *%s*%s*)
-               GPRINTF_MSG=$(gprintf "$1" "$2" "$3")
-               shift 3;;
-       *%s*)
-               GPRINTF_MSG=$(gprintf "$1" "$2")
-               shift 2;;
-       *)
-               GPRINTF_MSG=$(gprintf "$1")
-               shift;;
-esac
-GPRINTF_REST="$@"
-}
-
-
-
 # Check if $pid (could be plural) are running
 checkpid() {
 	while [ "$1" ]; do
@@ -115,7 +72,7 @@ daemon() {
 	nicelevel=0
 	while [ "$1" != "${1##-}" -o "$1" != "${1##+}" ]; do 
 	  case $1 in
-	    '')    gprintf "$0: Usage: daemon [+/-nicelevel] {program}\n" $0
+	    '')    echo $"$0: Usage: daemon [+/-nicelevel] {program}"
 	           return 1;;
 	    --check)
 	           shift
@@ -169,7 +126,7 @@ killproc() {
 	RC=0
 	# Test syntax.
 	if [ $# = 0 ]; then
-		gprintf "Usage: killproc {program} [signal]\n"
+		echo $"Usage: killproc {program} [signal]"
 		return 1
 	fi
 
@@ -241,7 +198,7 @@ pidofproc() {
 
 	# Test syntax.
 	if [ $# = 0 ] ; then
-		echo "Usage: pidofproc {program}"
+		echo $"Usage: pidofproc {program}"
 		return 1
 	fi
 
@@ -267,14 +224,14 @@ status() {
 
 	# Test syntax.
 	if [ $# = 0 ] ; then
-		gprintf "Usage: status {program}\n"
+		echo $"Usage: status {program}"
 		return 1
 	fi
 
 	# First try "pidof"
 	pid=`pidof -o $$ -o $PPID -o %PPID -x ${base}`
 	if [ "$pid" != "" ] ; then
-	        gprintf "%s (pid %s) is running...\n" "${base}"  "$pid"
+	        echo $"${base} (pid $pid) is running..."
 	        return 0
 	fi
 
@@ -282,16 +239,16 @@ status() {
 	if [ -f /var/run/${base}.pid ] ; then
 	        pid=`cat /var/run/${base}.pid | { read foo ; echo $foo ; }`
 	        if [ "$pid" != "" ] ; then
-	                gprintf "%s dead but pid file exists\n" "${base}"
+	                echo $"${base} dead but pid file exists"
 	                return 1
 	        fi
 	fi
 	# See if /var/lock/subsys/${base} exists
 	if [ -f /var/lock/subsys/${base} ]; then
-		gprintf "%s dead but subsys locked\n" "${base}"
+		echo $"${base} dead but subsys locked"
 		return 2
 	fi
-	gprintf "%s is stopped\n" "${base}"
+	echo $"${base} is stopped"
 	return 3
 }
 
@@ -299,7 +256,7 @@ echo_success() {
   [ "$BOOTUP" = "color" ] && $MOVE_TO_COL
   echo -n "[  "
   [ "$BOOTUP" = "color" ] && $SETCOLOR_SUCCESS
-  gprintf "OK"
+  echo -n $"OK"
   [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
   echo -n "  ]"
   echo -ne "\r"
@@ -310,7 +267,7 @@ echo_failure() {
   [ "$BOOTUP" = "color" ] && $MOVE_TO_COL
   echo -n "["
   [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
-  gprintf "FAILED"
+  echo -n $"FAILED"
   [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
   echo -n "]"
   echo -ne "\r"
@@ -321,7 +278,7 @@ echo_passed() {
   [ "$BOOTUP" = "color" ] && $MOVE_TO_COL
   echo -n "["
   [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
-  gprintf "PASSED"
+  echo -n $"PASSED"
   [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
   echo -n "]"
   echo -ne "\r"
@@ -330,14 +287,12 @@ echo_passed() {
 
 # Log that something succeeded
 success() {
-  gprintf_msg_rest "$@"
   if [ -z "$IN_INITLOG" ]; then
-     initlog $INITLOG_ARGS -n $0 -s "$GPRINTF_MSG" -e 1
+     initlog $INITLOG_ARGS -n $0 -s "$1" -e 1
   else
      # silly hack to avoid EPIPE killing rc.sysinit
      trap "" SIGPIPE
-# FIXME?
-     echo "$INITLOG_ARGS -n $0 -s \"$1\" -e 1" >&21
+     echo $"$INITLOG_ARGS -n $0 -s \"$1\" -e 1" >&21
      trap - SIGPIPE
   fi
   [ "$BOOTUP" != "verbose" ] && echo_success
@@ -347,12 +302,11 @@ success() {
 # Log that something failed
 failure() {
   rc=$?
-  gprintf_msg_rest "$@"
   if [ -z "$IN_INITLOG" ]; then
-     initlog $INITLOG_ARGS -n $0 -s "$GPRINTF_MSG" -e 2
+     initlog $INITLOG_ARGS -n $0 -s "$1" -e 2
   else
      trap "" SIGPIPE
-     echo "-n $0 -s \"$GPRINTF_MSG\" -e 1" >&21
+     echo $"$INITLOG_ARGS -n $0 -s \"$1\" -e 2" >&21
      trap - SIGPIPE
   fi
   [ "$BOOTUP" != "verbose" ] && echo_failure
@@ -362,13 +316,11 @@ failure() {
 # Log that something passed, but may have had errors. Useful for fsck
 passed() {
   rc=$?
-  gprintf_msg_rest "$@"
   if [ -z "$IN_INITLOG" ]; then
-     initlog $INITLOG_ARGS -n $0 -s "$GPRINTF_MSG" -e 1
+     initlog $INITLOG_ARGS -n $0 -s "$1" -e 1
   else
      trap "" SIGPIPE
-#FIXME?
-     echo "$INITLOG_ARGS -n $0 -s \"$1\" -e 1" >&21
+     echo $"$INITLOG_ARGS -n $0 -s \"$1\" -e 1" >&21
      trap - SIGPIPE
   fi
   [ "$BOOTUP" != "verbose" ] && echo_passed
@@ -377,9 +329,10 @@ passed() {
 
 # Run some action. Log its output.
 action() {
-  gprintf_msg_rest "$@"
-  echo -n "$GPRINTF_MSG "
-  initlog $INITLOG_ARGS -c "$GPRINTF_REST" && success "$GPRINTF_MSG" || failure "$GPRINTF_MSG"
+  STRING=$1
+  echo -n $"$STRING "
+  shift
+  initlog $INITLOG_ARGS -c "$*" && success $"$STRING" || failure $"$STRING"
   rc=$?
   echo
   return $rc
@@ -393,23 +346,20 @@ strstr() {
   return 0
 }
 
-
 # Confirm whether we really want to run this service
 confirm() {
-  gprintf "Start service %s (Y)es/(N)o/(C)ontinue? [Y] " $1
-  local YES=`gprintf "yY"`
-  local NOT=`gprintf "nN"`
-  local CNT=`gprintf "cC"`
-
+  local YES=$"yY"
+  local NO=$"nN"
+  local CONT=$"cC"
+  
+  echo -n $"Start service $1 (Y)es/(N)o/(C)ontinue? [Y] "
   read answer
-
   if strstr "$YES" "$answer" || [ "$answer" = "" ] ; then
-    return 0
-  elif strstr "$CNT" "$answer" ; then
-    return 2
-  elif strstr "$NOT" "$answer" ; then
-    return 1
+      return 0
+  elif strstr "$CONT" "$answer" ; then
+     return 2
+  elif strstr "$NO" "$answer" ; then
+     return 1
   fi
   confirm $*
-
 }
diff --git a/sysconfig/network-scripts/ifdown b/sysconfig/network-scripts/ifdown
--- a/sysconfig/network-scripts/ifdown
+++ b/sysconfig/network-scripts/ifdown
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
 TEXTDOMAIN=initscripts
 
@@ -9,13 +9,13 @@ cd /etc/sysconfig/network-scripts
 CONFIG=$1
 
 [ -z "$CONFIG" ] && {
-    gprintf "usage: %s <device name>\n" ifdown >&2
+    echo $"usage: ifdown <device name>" >&2
     exit 1
 }
 
 [ -f "$CONFIG" ] || CONFIG=ifcfg-$CONFIG
 [ -f "$CONFIG" ] || {
-    gprintf "usage: %s <device name>\n" ifdown >&2
+    echo $"usage: ifdown <device name>\n" >&2
     exit 1
 }
 
@@ -25,7 +25,7 @@ if [ $UID != 0 ]; then
 	    exec /usr/sbin/usernetctl $CONFIG down
 	fi
     fi
-    gprintf "Users cannot control this device.\n" >&2
+    echo $"Users cannot control this device." >&2
     exit 1
 fi
 
diff --git a/sysconfig/network-scripts/ifup b/sysconfig/network-scripts/ifup
--- a/sysconfig/network-scripts/ifup
+++ b/sysconfig/network-scripts/ifup
@@ -11,13 +11,13 @@ need_hostname
 CONFIG=${1}
 
 [ -z "${CONFIG}" ] && {
-    gprintf "usage: ifup <device name>\n" >&2
+    echo $"usage: ifup <device name>" >&2
     exit 1
 }
 
 [ -f "${CONFIG}" ] || CONFIG=ifcfg-${CONFIG}
 [ -f "${CONFIG}" ] || {
-    gprintf "usage: ifup <device name>\n" >&2
+    echo $"usage: ifup <device name>" >&2
     exit 1
 }
 
@@ -27,7 +27,7 @@ if [ ${UID} != 0 ]; then
 	    exec /usr/sbin/usernetctl ${CONFIG} up
 	fi
     fi
-    gprintf "Users cannot control this device.\n" >&2
+    echo $"Users cannot control this device." >&2
     exit 1
 fi
 
@@ -74,7 +74,7 @@ fi
 # is this device available? (this catches PCMCIA devices for us)
 LC_ALL= LANG= /sbin/ifconfig ${REALDEVICE} 2>&1 | grep -s "not found" > /dev/null
 if [ "$?" = "0" ]; then
-    gprintf "Delaying %s initialization.\n" "${DEVICE}"
+    echo $"Delaying ${DEVICE} initialization."
     exit 1
 fi
 
@@ -83,7 +83,7 @@ if [ "${SLAVE}" = yes -a "${ISALIAS}" = no -a "${MASTER}" != "" -a \
     RFLAG="" ; [ "${RECEIVEONLY}" = yes ] && RFLAG="-r"
 
     ifconfig ${DEVICE} down
-    gprintf "Enslaving %s to %s" "${DEVICE}" "${MASTER}"
+    echo $"Enslaving ${DEVICE} to ${MASTER}"
     ifenslave ${RFLAG} "${MASTER}" "${DEVICE}"
 
     exit 0
@@ -108,14 +108,14 @@ if [ -n "${DYNCONFIG}" ]; then
        PUMPARGS="${PUMPARGS} -d"
        DHCPDARGS="${DHCPDARGS} -R"
     fi
-    gprintf "Determining IP information for %s..." "${DEVICE}"
+    echo -n $"Determining IP information for ${DEVICE}..."
     
     if [ -x /sbin/pump ] && /sbin/pump ${PUMPARGS} -i ${DEVICE} ; then
-	gprintf " done.\n"
+	echo $" done."
     elif [ -x /sbin/dhcpcd ] && /sbin/dhcpcd ${DHCPCDARGS} ${DEVICE} ; then
-	gprintf " done.\n"
+	echo $" done."
     else
-	gprintf " failed.\n"
+	echo $" failed."
 	exit 1
     fi
 else 
diff --git a/sysconfig/network-scripts/ifup-aliases b/sysconfig/network-scripts/ifup-aliases
--- a/sysconfig/network-scripts/ifup-aliases
+++ b/sysconfig/network-scripts/ifup-aliases
@@ -62,7 +62,7 @@ TEXTDOMAIN=initscripts
 
 device=$1
 if [ "$device" = "" ]; then
-	gprintf "usage: %s <net-device>\n" "$0"
+	echo $"usage: ifup-aliases <net-device>\n"
 	exit 1
 fi
 
@@ -104,7 +104,7 @@ eval ` (
 # read defaults from the parent config file
 PARENTCONFIG=ifcfg-$device
 [ -f $PARENTCONFIG ] || {
-       echo "Missing config file $PARENTCONFIG." >&2
+       echo $"Missing config file $PARENTCONFIG." >&2
        exit 1
 }
 eval ` (
@@ -145,15 +145,15 @@ function new_interface ()
        ";
 
        if [ -n "$ipseen" ]; then
-              echo "error in $FILE: already seen ipaddr $IPADDR in $ipseen" >&2;exit 0
+              echo $"error in $FILE: already seen ipaddr $IPADDR in $ipseen" >&2;exit 0
        fi
 
        if [ -n "$devseen" ]; then
-              echo "error in $FILE: already seen device $parent_device:$DEVNUM\ in $devseen" >&2; exit 0
+              echo $"error in $FILE: already seen device $parent_device:$DEVNUM\ in $devseen" >&2; exit 0
        fi
        
        if [ -z "$DEVICE" -o -z "$IPADDR" ]; then
-              echo "error in $FILE: didn't specify device or ipaddr" >&2 ; exit 0
+              echo $"error in $FILE: didn't specify device or ipaddr" >&2 ; exit 0
        fi
 
        if [ -z "$NETMASK" ]; then
@@ -219,7 +219,7 @@ function new_interface ()
                                setup_this=yes
                        fi
                        if [ -n "$rdev_mark" -a "$rdev_mark" != "$newmark" ]; then
-                               echo "error in ifcfg-${parent_device}:\* files" >&2 ; exit 0
+                               echo $"error in ifcfg-${parent_device}:\* files" >&2 ; exit 0
                        fi
                        eval " rdev_${DEVNUM}_mark=\$newmark ";
                else
@@ -229,7 +229,7 @@ function new_interface ()
                if [ -n "$rdevip" -a "$rdevip" != "${DEVNUM}" ]; then
                        eval " mark_remove=\$rdev_${rdevip}_mark ";
                        if [ -n "$mark_remove" -a "$mark_remove" != "remove" ]; then
-                               echo "error in ifcfg-${parent_device}:\* files" >&2 ; exit 0
+                               echo $"error in ifcfg-${parent_device}:\* files" >&2 ; exit 0
                        fi
                        if [ "$mark_remove" != "remove" ]; then
                                eval " rdev_${rdevip}_mark=remove ";
@@ -334,11 +334,11 @@ for FILE in ifcfg-${parent_device}-range* ; do
        ipaddr_endnum=${IPADDR_END##*.}
 
        if [ "${IPADDR_START%.*}" != "${IPADDR_END%.*}" ]; then
-               echo "error in $FILE: IPADDR_START and IPADDR_END don't argree" >&2; exit 0
+               echo $"error in $FILE: IPADDR_START and IPADDR_END don't argree" >&2; exit 0
        fi
 
        if [ $ipaddr_startnum -gt $ipaddr_endnum ]; then
-               echo "error in $FILE: IPADDR_START greater than IPADDR_END" >&2; exit 0
+               echo $"error in $FILE: IPADDR_START greater than IPADDR_END" >&2; exit 0
        fi
 
        ipaddr_num=$ipaddr_startnum
